#! /bin/bash

about(){

}

ShowDoing(){
    echo “> 正在进行”$1“...“
}

ShowDone(){
    echo "> "$1"加固完成。"
}

SecureReinforce(){
    if [[ -n $1 ]];then
        
    fi
    local PASS_MIN_MODIFY="10"
    local PASS_MAX_MODIFY="8"
    
    local SYSTEM_AUTH="/etc/pam.d/system-auth"
    local PAM_SSHD="/etc/pam.d/sshd"
    
    ShowDoing "密码"
    sed -i "/Permit" $SYSTEM_AUTH
    ShowDone “密码”
    
}

chooseAutoOrManually(){
    echo "************ 正在进行系统安全加固 "************"
    echo "> 是否选择默认安全配置进行加固，自动/默认配置（Y），手动配置（N）：" mode
    case $mode in 
        [Y,y])
            SecureReinforce
        ;;
        [N,n])
            SecureReinforce
        ;;
        *)
            echo "请正确输入(y)或者(n)。"
}

main(){
    clear
    about
    chooseAutoOrManually
}

main
